# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ridge_closed_form_result <- function(x, y, lam, w, eta, x_val, y_val, standard) {
    .Call('_angleTL_ridge_closed_form_result', PACKAGE = 'angleTL', x, y, lam, w, eta, x_val, y_val, standard)
}

